name: Code Quality

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    ESLint:
        name: ESLint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@v2
            - name: Use Node.js 16.9.0
              uses: actions/setup-node@v2
              with:
                  node-version: 16.9.0
                  cache: yarn
            - name: Restore CI Cache
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.os }}-16-${{ hashFiles('**/yarn.lock') }}
            - name: Install Dependencies
              run: yarn --frozen-lockfile
            - name: Run ESLint
              run: yarn test:lint

    Typescript:
        name: Typescript
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@v2
            - name: Use Node.js 16.9.0
              uses: actions/setup-node@v2
              with:
                  node-version: 16.9.0
                  cache: yarn
            - name: Restore CI Cache
              uses: actions/cache@v1
              with:
                  path: node_modules
                  key: ${{ runner.os }}-16-${{ hashFiles('**/yarn.lock') }}
            - name: Install Dependencies
              run: yarn --frozen-lockfile
            - name: Run TSC
              run: yarn dev:build